name: RoSys
root: ./
# startup_window: takeoff
# tmux_options: -f tmux.conf
windows:
  - UR10e:
      layout: tiled
      #synchronize: after
      panes:
        - pane1:
          - source $HOME/ur_ws/devel/setup.bash
          - roslaunch ur_gazebo ur10e_bringup.launch robot_ip:=127.0.0.1
                
        - pane2:
          - 'source $HOME/ur_ws/devel/setup.bash;
            sleep 2;
            roslaunch ur10e_moveit_config demo.launch config:=true'
        - pane3:
          - 'source $HOME/ur_ws/devel/setup.bash;
            sleep 3;
            roslaunch ur10e_moveit_config ur10e_moveit_planning_execution.launch sim:=true'

        - pane4:
          - 'source $HOME/ur_ws/devel/setup.bash;
            sleep 4;
            rostopic list'
          
